import csv

from .schema import (
    BEANS_TABLE,
    BEANS_COL_ID,
    BEANS_COL_PURCHASE_DATE,
    BEANS_COL_ROASTER,
    BEANS_COL_BLEND_NAME,
    BEANS_COL_ROAST_LEVEL,
    BEANS_COL_ROAST_DATE,
    BEANS_COL_WEIGHT_GRAMS,
    BEANS_COL_TASTING_NOTES,
    BEANS_COL_ORIGIN_COUNTRY,
    BEANS_COL_PROCESSING_METHOD,

    ROASTERS_TABLE,
    ROASTERS_COL_ID,
    ROASTERS_COL_NAME,
    ROASTERS_COL_CITY,
    ROASTERS_COL_STATE,
    ROASTERS_COL_WEBSITE
)

CREATE_COFFEE_BEANS_TABLE = f'''
CREATE TABLE IF NOT EXISTS {BEANS_TABLE} (
    {BEANS_COL_ID} INTEGER PRIMARY KEY AUTOINCREMENT,
    {BEANS_COL_PURCHASE_DATE} TEXT,
    {BEANS_COL_ROASTER} TEXT,
    {BEANS_COL_BLEND_NAME} TEXT,
    {BEANS_COL_ROAST_LEVEL} TEXT,
    {BEANS_COL_ROAST_DATE} TEXT,
    {BEANS_COL_WEIGHT_GRAMS} REAL,
    {BEANS_COL_TASTING_NOTES} TEXT,
    {BEANS_COL_ORIGIN_COUNTRY} TEXT,
    {BEANS_COL_PROCESSING_METHOD} TEXT
)
'''

CREATE_COFFEE_ROASTER_TABLE = f'''
CREATE TABLE IF NOT EXISTS {ROASTERS_TABLE} (
    {ROASTERS_COL_ID} INTEGER PRIMARY KEY AUTOINCREMENT,
    {ROASTERS_COL_NAME} TEXT,
    {ROASTERS_COL_CITY} TEXT,
    {ROASTERS_COL_STATE} TEXT,
    {ROASTERS_COL_WEBSITE} TEXT
)
'''

INSERT_INTO_BEANS_TABLE = f'''
INSERT INTO {BEANS_TABLE} (
    {BEANS_COL_PURCHASE_DATE},
    {BEANS_COL_ROASTER},
    {BEANS_COL_BLEND_NAME},
    {BEANS_COL_ROAST_LEVEL},
    {BEANS_COL_ROAST_DATE},
    {BEANS_COL_WEIGHT_GRAMS},
    {BEANS_COL_TASTING_NOTES},
    {BEANS_COL_ORIGIN_COUNTRY},
    {BEANS_COL_PROCESSING_METHOD}
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
'''

INSERT_INTO_ROASTERS_TABLE = f'''
INSERT INTO {ROASTERS_TABLE} (
    {ROASTERS_COL_NAME},
    {ROASTERS_COL_CITY},
    {ROASTERS_COL_STATE},
    {ROASTERS_COL_WEBSITE}
) VALUES (?, ?, ?, ?)
'''

def preview_table(conn, table: str, limit: int = 5):
    cursor = conn.cursor()
    cursor.execute(f'SELECT * FROM {table} LIMIT {limit}')
    return cursor.fetchall()
